[workspace]
resolver = "2"
members = ["crates/account_sdk"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
base64 = "0.21.5"
cainome = { git = "https://github.com/cartridge-gg/cainome", tag = "v0.1.0", features = [
    "abigen-rs",
] }
cairo-lang-starknet = "2"
futures = "0.3"
lazy_static = "1.4.0"
p256 = "0.13.2"
primitive-types = { version = "0.12", default-features = false }
rand_core = { version = "0.6.4", features = ["getrandom"] }
serde = "1"
serde_json = "1"
sha2 = "0.10.8"
starknet = "0.8.0"
starknet-crypto = "0.6.1"
thiserror = "1"
tokio = { version = "1.0", features = ["macros"] }
toml = "0.8"
u256-literal = "1.2.1"
url = "2"
wasm-bindgen = "0.2"
webauthn-authenticator-rs = { version = "0.4.9" }
webauthn-rs-proto = "0.4.9"
