[package]
name = "webauthn"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
alexandria_encoding = { path = "lib/alexandria/alexandria/encoding" }
alexandria_math = { path = "lib/alexandria/alexandria/math" }
