[workspace]
members = [
    "src/auth",
    "src/session"
]
name = "webauthn"
version = "0.1.0"
description = "Cairo webauthn library"
homepage = "https://github.com/keep-starknet-strange/alexandria/"

[workspace.dependencies]

[scripts]
all = "scarb build && scarb test"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest
