[workspace]
members = [
    "crates/cartridge_account",
    "crates/webauthn/auth",
    "crates/webauthn/session",
]

[workspace.package]
edition = "2023_10"
version = "0.1.0"

[workspace.dependencies]
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria", commit = "085f17c87cf6d168032ef5840c39b8e18012284f" }
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria", commit = "085f17c87cf6d168032ef5840c39b8e18012284f" }
alexandria_merkle_tree = { git = "https://github.com/keep-starknet-strange/alexandria", commit = "085f17c87cf6d168032ef5840c39b8e18012284f" }
starknet = "2.2.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest
