[package]
description = "Webauthn authentication library"
edition.workspace = true
name = "webauthn_auth"
version.workspace = true

[dependencies]
alexandria_encoding.workspace = true
starknet.workspace = true
