[package]
description = "Session token library"
edition.workspace = true
name = "webauthn_session"
version.workspace = true

[dependencies]
alexandria_data_structures.workspace = true
alexandria_encoding.workspace = true
alexandria_merkle_tree.workspace = true
starknet.workspace = true
