[package]
name = "webauthn_session"
version = "0.1.0"
description = "Session token library"
homepage = "https://github.com/cartridge-gg/cairo-webauthn/tree/main/src/session"

[dependencies]
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria", commit="085f17c87cf6d168032ef5840c39b8e18012284f" }
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria", commit="085f17c87cf6d168032ef5840c39b8e18012284f" }
alexandria_merkle_tree = { git = "https://github.com/keep-starknet-strange/alexandria", commit="085f17c87cf6d168032ef5840c39b8e18012284f" }
