[package]
name = "webauthn_auth"
version = "0.1.0"
description = "Webauthn authentication library"
homepage = "https://github.com/cartridge-gg/cairo-webauthn/tree/main/src/auth"

[dependencies]
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria", tag="cairo-v2.3.0-rc0" }
starknet = "2.2.0"
